name: "multi event pipeline/ workflow"

on:
    push: 
        branches:
            - master
            - test

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push/test push"
              run: echo "Running on master push"
